# Generated by Django 3.1 on 2020-08-23 02:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0002_auto_20200822_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='price',
            field=models.TextField(max_length=50),
        ),
    ]
